.TH _PRINTF 3 "July 27, 2021" "Version 1.0" "_printf man page"
.SH NAME
_printf
.SH SYNOPSIS
.B #include <holberton.h>

.B int _printf(const char *format, ...);
." There are important helper functions prototypes declared in holberton.h
." that was not mentioned here to reduce redundancy and since _printf is our focus.

.SH DESCRIPTION
.B _printf
is a replica of the standard printf function. It tries to simulate the same functionalities
that
.B printf
possesses.

." Note:
.PP
.B Remember this is just a clone and may not possess all features that printf has.
This was the first group project we worked on at ALX. And there is one thing it left me
with; respect for
.B the standard printf() function.

.SH PARAMETERS
.TP
.B format
string to be parsed based on the presence or absence of specifiers
.TP
.IP ...
This can consist of zero or more passed arguments
.PP
.I Remember that printf is a variadic function.

.SH AUTHOR
.PP
.B OVECJOE
- A Nigerian Ethical Hacker to be; I was a coding addict.
